### ISSUE TITLE
Segfault running openrabbitfu without any parameters

### ISSUE THREAD

**Issue by tomlogic** [spth/OpenRabbit#16]
With a build on my Mac, ran into this:
```
[tom@tbc-mbp src]$ ./openrabbitfu
Segmentation fault: 11
```

Without looking at the code, I'm guessing it's checking `argv[]` without looking at `argc`.

Help works:
```
[tom@tbc-mbp src]$ ./openrabbitfu -?
Usage: openrabbitfu [dc8pilot] <coldload.bin> <pilot.bin> <project.bin> <cable device>
Usage: openrabbit [dc8pilot] <coldload.bin> <pilot.bin> <project.bin> <project.brk> <drive> <mount> <cable device>
```

But I'm having some serial port troubles so I'm going to switch over to Windows and try building/testing there (using MSYS2).

**Comment by spth** [comment]
Fixed in dfd2a73.
